### ISSUE TITLE
Invalid data

### ISSUE THREAD

**Issue by brisa-pedronetto** [mircoc/cordova-plugin-settings-hook#1]
Hey guys, thank you so much for this plugin, it will be really useful!  I just installed it and got an error, any ideas?

```
pedroshost:book-viewer pedronetto$ cordova plugins add cordova-plugin-settings-hook
Fetching plugin "cordova-plugin-settings-hook" via npm
npm http GET https://registry.npmjs.org/cordova-plugin-settings-hook
npm http 304 https://registry.npmjs.org/cordova-plugin-settings-hook
Installing "cordova-plugin-settings-hook" for android
Installing "cordova-plugin-settings-hook" for ios
pedroshost:book-viewer pedronetto$ cordova build android
Processing settings for platform: android
TypeError: invalid data
    at WriteStream.Socket.write (net.js:614:11)
    at /Users/Development/L/book-viewer/plugins/cordova-plugin-settings-hook/updatePlatformConfig.js:355:36
    at Array.forEach (native)
    at /Users/Development/L/book-viewer/plugins/cordova-plugin-settings-hook/updatePlatformConfig.js:349:23
    at module.exports (/Users/Development/L/book-viewer/plugins/cordova-plugin-settings-hook/updatePlatformConfig.js:359:7)
    at runScriptViaModuleLoader (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:152:18)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:130:16)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:115:20
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
```

**Comment by mircoc** [comment]
Hello @brisa-pedronetto thank you for the bug report, can you send me a minimal cordova project to reproduce the error. It would help a lot. Thanks

**Comment by Tenvan** [comment]
Hi,
you get the same error, if you adds an platform other than 'ios' or 'android' (windows for example).
also ios works by me, but android not... 

here my config.xml:


[config.xml.txt](https://github.com/mircoc/cordova-plugin-settings-hook/files/63865/config.xml.txt)

**Comment by Tenvan** [comment]
Here with not working Android Config..

[config.xml.txt](https://github.com/mircoc/cordova-plugin-settings-hook/files/63869/config.xml.txt)

**Comment by brisa-pedronetto** [comment]
Hey there @mircoc, thanks for the quick reply! I tried with a minimal project and it worked fine. So now I'm trying to figure what is causing it in my project. Will come back with more updates on this soon.

**Comment by brisa-pedronetto** [comment]
I tried creating a new cordova project (mine was about 1 year old, but I updated some things without starting from scratch) and it worked. Maybe it was just a compatibility issue. Thanks @mircoc!

**Comment by mircoc** [comment]
@brisa-pedronetto @Tenvan 
I just updated the package on npm also. Version 0.1.1 solve this issue. It was raised when a platform different from iOS or Android was available. If you find any more issue let me know. Thanks!

**Comment by claudioviola** [comment]
Hello @mircoc 
Thanks! your plugin is very usefull. For iOS works perfectly.
But when I try tu run "ionic build android". I've an error of "Error: invalid data"
I'm using 0.2.3 and in my config.xml.
Can you support me to solve the issue?
Thanks a lot again!
Claudio

**Comment by mircoc** [comment]
Hello @claudioviola,
thanks for the bug report!
To solve your issue you need to add android namespace to the xml root of your config.xml, please take a look here:
https://github.com/mircoc/cordova-plugin-settings-hook/blob/master/README.md#android-config-file-requirements

Let me know
Mirco

**Comment by claudioviola** [comment]
Hello @mircoc 
Thanks for support! It works!
