### ISSUE TITLE
iOS .plist error with Ionic 3.4.0 / Cordova 7.0.1

### ISSUE THREAD

**Issue by danielflippance** [mircoc/cordova-plugin-settings-hook#12]
When using this plugin with Ionic 3.4.0 and Cordova 7.0.1, and then adding the ios platform, the resulting .plist file is missing `<string>` elements for NSMainNibFile & NSMainNibFile~ipad

    $ Ionic cordova platform add ios

The result is missing <string/> tags in the .plist file. /platforms/ios/myapp.plist:

```
    <key>NSMainNibFile</key>
    <key>NSMainNibFile~ipad</key>
    <key>UISupportedInterfaceOrientations</key>
    ....
```

I expected this to look like:

```
    <key>NSMainNibFile</key>
    <string></string>
    <key>NSMainNibFile~ipad</key>
    <string></string>
    <key>UISupportedInterfaceOrientations</key>
    ....
```

Running the app results in the error:

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', 
reason: 'Could not load NIB in bundle: 'NSBundle 
</var/containers/Bundle/Application/78ABCDC1-ABCD-ABCD-9793-891421ABCDB8/myapp.app>
 (loaded)' with name 'NSMainNibFile~ipad''
```

Removing this plugin fixes the problem

I have the following setup on Ionic:

```
$ ionic info

global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : ios 4.4.0
    Ionic Framework                 : ionic-angular 3.4.0

System:

    Node       : v6.10.0
    OS         : OS X El Capitan
    Xcode      : Xcode 8.2.1 Build version 8C1002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
    npm        : 3.10.10 
```

From package.json:
```
        "cordova-plugin-settings-hook": "0.2.5",
```

**Comment by mircoc** [comment]
Hi @danielflippance, thanks for your bug report! I found an issue in a dependent module  https://github.com/TooTallNate/plist.js/issues/79  that they fixed in a new release so I changed the dependencies to this new version.
I just released v0.2.6 that fixes this. Try it and let me know!
