### ISSUE TITLE
Building fails with "Error: Cannot find module 'plist'"

### ISSUE THREAD

**Issue by EmielH** [mircoc/cordova-plugin-settings-hook#13]
After updating to version 0.2.6, all builds (even Android ones) fail with `Error: Cannot find module 'plist'`. Reverting the version back to 0.2.5 makes the builds work again. Is there something I need to change in the configuration before being able to use version 0.2.6?

Someone else reported this problem as well, on the Ionic Forums: https://forum.ionicframework.com/t/ionic-package-build-fails-error-cannot-find-module-plist/96585

**Comment by janpio** [comment]
Does this only happen with Ionic Package or also locally?
Ionic Package is a special kind of environment, especially hooks are quite limited there.

**Comment by EmielH** [comment]
For the person on the forums apparently it happened in Ionic Package. For me, it happens locally when I build on our Jenkins server.

**Comment by janpio** [comment]
Ok, then it's not an Ionic Package thing. Carry on ;)

**Comment by mircoc** [comment]
Hi guys, I introduced a dependency to resolve an issue with pList file on iOS. That's the cause of this bug.
I'm working on a new version that includes the dependency inside the same file, so Cordova doesn't need to install anything.
I'll publish the update today, hopefully.
Stay tuned :)
Thanks.

**Comment by mircoc** [comment]
Just pushed on npm version 0.2.7, please update and let me know if it works for you thanks! @EmielH @janpio

**Comment by EmielH** [comment]
It's working again for me. Thanks a lot!
