### ISSUE TITLE
Error: invalid data

### ISSUE THREAD

**Issue by samodadela** [mircoc/cordova-plugin-settings-hook#2]
Hi, 

What I did:
`cordova plugin add https://github.com/mircoc/cordova-plugin-settings-hook`

Added the following to config.xml:
```
   <platform name="android">
    <config-file target="AndroidManifest.xml" parent="/*">
      <uses-permission android:name="android.permission.READ_CONTACTS" android:maxSdkVersion="15"/>
      <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
    </config-file>
   </platform>
```

And I get the dreaded invalid data. The problem is with the parent tag. The examples are wrong since they use invalid xml:
```
<config-file target="AndroidManifest.xml" parent="/*>  <- note that there is no ending quote in parent
        <supports-screens
```

Next I tried to set parent="manifest" (because I want to insert stuff under manifest). There is no error, but the file isn't changed either.

FYI: I then saw the demo directory... run cordova platform add android -> Error: invalid data

**Comment by samodadela** [comment]
# cordova -v
6.0.0

**Comment by samodadela** [comment]
Mirco, thanks for updating the readme. 

I still get the same error. I'm willing to debug it, but I don't know how - tried using node-inspector but I can't attach to it (only to the parent node.exe). How do you debug it?

**Comment by mircoc** [comment]
Thank you for your very detailed bug report!

Can you send to me your config.xml, so i can reproduce the bug on my machine ?

**Comment by samodadela** [comment]
Of course, here it is...
[config.zip](https://github.com/mircoc/cordova-plugin-settings-hook/files/157707/config.zip)

The /* will cause invalid data: 
`<config-file platform="android" target="AndroidManifest.xml" parent="/*">  `

The next line will not cause the invalid data error, but doesn't work (I want to insert stuff under manifest, same level as uses-permission):
`<config-file platform="android" target="AndroidManifest.xml" parent="manifest">  `

I did some debugging but it's getting weirder ;) Put a lot of console.log's throughout the code but I'm getting the error at different places... also the error seems to be printed from the catch block in main but if you put another console.log after the stdout.write(e) - it's not displayed. [sorry I'm very new to js]

After some investigation... found this:
```
data = {
  "_id": 1239,
  "tag": "supports-screens",
  "attrib": {
    "android:xlargeScreens": "false",
    "android:largeScreens": "false",
    "android:smallScreens": "false"
  },
  "text": "",
  "tail": "\n            ",
  "_children": []
}
```

-> executes till here

```
// copy all config.xml data except for the generated _id property
                        data.forEach( function (prop, propName) {
```
-> this is never reached

I guess the problem is in data.forEach...Isn't forEach supposed to work on arrays ([]) and not objects ({})?

Excuse my noobnes ;)

**Comment by samodadela** [comment]
Grazie mille! Works perfectly now.

BTW: Can you please update the cordova plugins registry so that 'cordova plugin add' fetches the latest version? Or is that not in your control?

**Comment by mircoc** [comment]
I just updated also npm. I had an issue doing it because a demo project were making the upload too big and npm refusing update. Now i solved it adding a .npmignore and we have 0.2.2 available.

**Comment by samodadela** [comment]
Thanks!

**Comment by saijanu** [comment]
Hi,
If I want to replace an element defined within the config-file how can I do that. Below one is not working for android. It's get appended to the same element
`<config-file target="AndroidManifest.xml" parent="application">
            <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/fb_app_id"/>
</config-file>`
