### ISSUE TITLE
android-windowSoftInputMode not working

### ISSUE THREAD

**Issue by hayuki** [mircoc/cordova-plugin-settings-hook#8]
Hello! Firstly, thanks a lot for the plugin, it is extremely useful :)

However, there is one issue I hoped it would solve, but it does not seem to work as expected. I am currently building an Ionic 2 project, and by default the `windowSoftInputMode` attribute in the MainActivity of the AndroidManifest is set to "adjustResize". I need to set it to "adjustPan", and there isn't a way to set that attribute through the standard Cordova preferences. 

This plugin has `android-windowSoftInputMode` in the custom preferences, and I expected it to change the default value set by Ionic. However, when I run `$cordova prepare`, any new values (e.g. `android-activity-hardwareAccelerated` or `android-installLocation`) are generated in the manifest correctly, but `windowSoftInputMode` always keeps the default Ionic value of "adjustResize". I tried re-adding the android platform, as well as manually deleting the `windowSoftInputMode` attribute from the generated manifest and re-running `$cordova prepare` (in which case the attribute never regenerated)... nothing seems to help.  

Is there something I'm missing?

**Comment by hayuki** [comment]
Right, just as I posted this issue I looked at your implementation and noticed that to change the activity's attributes the plugin looks for an activity with the name "CordovaApp". However, in the latest version of Cordova they renamed the activity to 'MainActivity', so none of the activity hooks in your plugin work on the newer version anymore. Another custom cordova config plugin, developed by @dpa99c, had the same issue, but it has been resolved by now (look [here](https://github.com/dpa99c/cordova-custom-config/issues/1)). I suggest you apply the same changes to the code :)

I think I'll switch to @dpa99c's plugin so long...

**Comment by mircoc** [comment]
Hello @hayuki , thanks for the very helpful bug report! I didn't notice that the plugin don't works with newer version of Cordova Android platform.
Now i should have solved it. I introduced a new algorithm to find the main Android Activity, so if Cordova team change again the name of the main activity it should continue to get it :)
If you have time to test it let me know if it works, i updated version to 0.2.4 on npm.
Thanks again!
